apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - redis/deployment.yaml
  - redis/service.yaml
  - api/deployment.yaml
  - api/service.yaml
  - auth/deployment.yaml
  - auth/service.yaml
  - ws/deployment.yaml
  - ws/service.yaml
  - ws/pvc.yaml
  - ws/pdb.yaml
  - cron/deployment.yaml
  - cron/service.yaml